import = [
  "/home/rafael/.nvm/versions/node/v20.12.2/lib/node_modules/alacritty-themes/themes/Gruvbox-Dark.toml"
]

[shell]
program = "/bin/bash"

[font]
size = 14

	[font.normal]
  family = "JetBrains Mono"
  style = "Regular"
