let mapleader = " "

syntax on

filetype plugin indent on

" set number
set relativenumber

set tabstop=4
set shiftwidth=4
set expandtab

set autoindent
set smartindent

set hlsearch
set incsearch

set showmatch

set scrolloff=3

set noerrorbells
set novisualbell
set t_vb=

autocmd FileType c setlocal shiftwidth=4 tabstop=4 expandtab
autocmd FileType cpp setlocal shiftwidth=4 tabstop=4 expandtab

" keymaps
nnoremap <leader>pv :Ex<CR>

" edit and save vimrc
nnoremap <leader>ev :e $MYVIMRC<CR>
nnoremap <leader>sv :source $MYVIMRC<CR>

" move lines
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv

nnoremap <A-J> :m .+1<CR>==
nnoremap <A-K> :m .-2<CR>==

" copy ~ paste
nnoremap <leader>y "+y
"nnoremap <leader>Y "+yg_
"nnoremap <leader>p "+p
"nnoremap <leader>P "+P
set clipboard=unnamedplus

" plugins
call plug#begin()

Plug 'junegunn/seoul256.vim'
Plug 'https://github.com/junegunn/vim-easy-align.git'
Plug 'tpope/vim-sensible'
Plug 'EdenEast/nightfox.nvim'

call plug#end()

" color scheme
colorscheme nightfox

